package com.ateca.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6e5e00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFfbe365)
val md_theme_light_onPrimaryContainer = Color(0xFF211b00)
val md_theme_light_secondary = Color(0xFF835500)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffddb0)
val md_theme_light_onSecondaryContainer = Color(0xFF2a1800)
val md_theme_light_tertiary = Color(0xFF405aa9)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFdae1ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001550)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffcf3)
val md_theme_light_onBackground = Color(0xFF1d1c16)
val md_theme_light_surface = Color(0xFFfffcf3)
val md_theme_light_onSurface = Color(0xFF1d1c16)
val md_theme_light_surfaceVariant = Color(0xFFe9e2d0)
val md_theme_light_onSurfaceVariant = Color(0xFF4b4739)
val md_theme_light_outline = Color(0xFF7c7768)
val md_theme_light_inverseOnSurface = Color(0xFFf5f0e7)
val md_theme_light_inverseSurface = Color(0xFF32302a)
val md_theme_light_inversePrimary = Color(0xFFdec74c)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFdec74c)
val md_theme_dark_onPrimary = Color(0xFF393000)
val md_theme_dark_primaryContainer = Color(0xFF524600)
val md_theme_dark_onPrimaryContainer = Color(0xFFfbe365)
val md_theme_dark_secondary = Color(0xFFffb94d)
val md_theme_dark_onSecondary = Color(0xFF462b00)
val md_theme_dark_secondaryContainer = Color(0xFF643f00)
val md_theme_dark_onSecondaryContainer = Color(0xFFffddb0)
val md_theme_dark_tertiary = Color(0xFFb4c5ff)
val md_theme_dark_onTertiary = Color(0xFF042978)
val md_theme_dark_tertiaryContainer = Color(0xFF264190)
val md_theme_dark_onTertiaryContainer = Color(0xFFdae1ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1c16)
val md_theme_dark_onBackground = Color(0xFFe6e2d9)
val md_theme_dark_surface = Color(0xFF1d1c16)
val md_theme_dark_onSurface = Color(0xFFe6e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF4b4739)
val md_theme_dark_onSurfaceVariant = Color(0xFFccc6b4)
val md_theme_dark_outline = Color(0xFF969181)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1c16)
val md_theme_dark_inverseSurface = Color(0xFFe6e2d9)
val md_theme_dark_inversePrimary = Color(0xFF6e5e00)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFf3eee8)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFF5b0a00)